#!/bin/bash

set -o errexit -o pipefail -o noclobber -o nounset

! getopt --test > /dev/null
if [[ ${PIPESTATUS[0]} -ne 4 ]]; then
    echo 'I’m sorry, `getopt --test` failed in this environment.'
    exit 1
fi

LONGOPTS=single-sided
OPTIONS=s

! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")
if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
    exit 2
fi

eval set -- "$PARSED"

s=n

while true; do
    case "$1" in
        -s|--single-sided)
            s=y
            shift
            ;;
        --)
            shift
            break
            ;;
        *)
            echo 'Error while parsing options'
            exit 3
            ;;
    esac
done

echo "Single-sided: $s"

# define print command
print_cmd="lpr -h -o media='a4' -T 'RBI ist cool'"
if [[ $s == "y" ]]; then
    print_cmd="$print_cmd -o sides=one-sided"
fi

for item in "$@" ;do
    echo "Es wird nun ""$item"" gedruckt"
    echo "Druckbefehl: ""$print_cmd"" ""$item"
    $print_cmd $item
    mv $item PDF
done
lpq
/opt/rbi/bin/lpquota

exit 0
